TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dh2000.db
DATA += dh2000.proto

#=======================================
include $(TOP)/configure/RULES
