TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dh2000.db
DATA += dh2000.proto

DB += error_setter.db

#=======================================
include $(TOP)/configure/RULES
